export const EVENT_BOOTSTRAP_COMPLETED = 'CORE:EVENT_BOOTSTRAP_COMPLETED';
export const EVENT_HTTP_REQUEST_TRANSACTION = 'CORE:EVENT_HTTP_REQUEST_TRANSACTION';
export const EVENT_HTTP_AUTH_ERROR = 'CORE:EVENT_HTTP_AUTH_ERROR';
export const EVENT_HTTP_NETWORK_ERROR = 'CORE:EVENT_HTTP_NETWORK_ERROR';
